docks fixes
GenPi64/genpi-tools pull request #5
Opened 2021-05-16 16:29 UTC by necrose99

added conf , etc ...

changed readme  to reflect https://github.com/GenPi64/genpi-tools/

2021-05-16 18:46 UTC, samip5 requested changes
Please correct your typoed links. Its tools not tool.

2021-05-18 01:39 UTC, necrose99 commented
ok amended...

2021-05-18 15:57 UTC, necrose99 commented on README.md
> +auto-sync = yess
Odd, verry odd. 

Noepad++ , chrome cut/paste.. 

My dyslexic hide less i run spell check ...

**But why that specificly shifted is very very odd.**.

I do know github added a ui to make fork syncs easier.... 

Network has flaked with the torrent of 🌧 ⛈  power too.. 

Great fix .... it.. 
Let me try and smash the commits... sqush.. bit all thumbs but will try and squash commits

2021-05-18 18:03 UTC, samip5 approved these changes

2021-05-18 18:04 UTC, merged